version: '3'

volumes:
  mysql_data:

networks:
  drift-net:

services:
  mysql_server:
    build: ./mysql/
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: drift_todo
      MYSQL_USER: devel
      MYSQL_PASSWORD: devel
    networks:
      - drift-net
